variables:
  DOCKER_IMAGE_REC: "${NEXUS_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest"
  DOCKER_IMAGE_PROD: "${NEXUS_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"

stages:
  - build

docker-build:
  stage: build
  tags:
    - devops
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  needs: [ ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${NEXUS_REGISTRY}\":{\"auth\":\"$(echo -n ${NEXUS_USER}:${NEXUS_PWD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --destination "${DOCKER_IMAGE}"
      --skip-tls-verify
      --skip-tls-verify-pull
      --insecure
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables: 
        DOCKER_IMAGE: $DOCKER_IMAGE_REC
    - if: $CI_COMMIT_TAG
      variables: 
        DOCKER_IMAGE: $DOCKER_IMAGE_PROD