version: '3.8'

services:
  pphook:
    image: pphook:1.0
    
    # Variables d'environnement (non sensibles)
    environment:
      - TZ=Europe/Paris
      - PYTHONUNBUFFERED=1
    
    # Secrets Docker
    secrets:
      - source: global_vars
        target: /opt/pphook/config.ini
    
    # Volumes pour persistance
    volumes:
      - pphook_data:/var/lib/pphook
      - pphook_logs:/var/log
    
    # Configuration réseau
    networks:
      - pphook_network
    
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Définition des secrets Docker Swarm
secrets:
  global_vars:
    name: global_vars-$CI_JOB_ID
    file: $GLOBAL_VARS


# Volumes persistants
volumes:
  pphook_data:
    driver: local
  pphook_logs:
    driver: local

# Réseau dédié
networks:
  pphook_network:
    driver: overlay
    attachable: true
